# //////////////////////////////////////////////////////////////////////////////////////////////////
# ///                                                                                            ///
# /// 1. Review the code in this file. Can you spot the bug?                                     ///
# /// 2. Fix the bug and push your solution so that GitHub Actions can run                       ///
# /// 3. You successfully completed this level when .github/workflows/jarvis-hack.yml pass 🟢    ///
# /// 4. If you get stuck, read the hint in hint-1.txt and try again                             /// 
# /// 5. If you need more guidance, read the hint in hint-2.txt and try again                    ///
# /// 6. Compare your solution with solution.yml. Remember, there are several possible solutions ///
# ///                                                                                            ///
# //////////////////////////////////////////////////////////////////////////////////////////////////

name: CODE - Jarvis Gone Wrong

on:
  push:
    paths:
      - ".github/workflows/jarvis-code.yml"

jobs:
  jarvis:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Check GitHub Status
        run: |
          STATUS=$(curl -s https://www.githubstatus.com/api/v2/status.json | jq -r '.status.description')
          echo "GitHub Status: $STATUS"
